name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        project:
          - Riverside.Markup
          - Riverside.Markup.CompilerServices
          - Riverside.Markup.InteropServices
          # Add more projects here as needed
        os: [windows-latest, ubuntu-latest]

    outputs:
      normalized_name: ${{ steps.normalize_name.outputs.normalized_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore src/${{ matrix.project }}/${{ matrix.project }}.csproj

      - name: Build project
        run: dotnet build src/${{ matrix.project }}/${{ matrix.project }}.csproj --configuration Release --no-restore

      - name: Pack project
        run: dotnet pack src/${{ matrix.project }}/${{ matrix.project }}.csproj --configuration Release --no-build -o ./output

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Packages (${{ matrix.project }})
          path: ./output/*.nupkg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Symbols (${{ matrix.project }})
          path: ./output/*.snupkg
